version: '3.8'

services:
  runner:
    build: 
      context: .
      dockerfile: Dockerfile.runner
    container_name: github-runner
    restart: unless-stopped
    environment:
      - RUNNER_NAME_PREFIX=horizon-stream
      - GITHUB_REPO=${GITHUB_REPO}
      - GITHUB_PAT=${GITHUB_PAT}
      # Optional: remove if you don't need custom labels
      - RUNNER_LABELS=rust,docker,self-hosted
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-data:/runner
      - cargo-cache:/opt/cargo
      - rustup-cache:/opt/rustup

  # Optional: Add PostgreSQL if needed
  # db:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

volumes:
  runner-data:
  cargo-cache:
  rustup-cache:
