[workspace]
members = [
    # "crates/api",
    "crates/storage",
    "crates/streaming",
    # "crates/video",
    # "crates/auth",
    "crates/common",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["vikpelle@gmail.com"]


[workspace.dependencies]
# Async runtime and web framework
tokio = { version = "1.36", features = ["full"] }
axum = { version = "0.7", features = ["multipart"] }
tower = "0.4"
async-trait = "0.1.83"
tower-http = { version = "0.5", features = ["trace", "cors"] }
futures = "0.3.31"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Storage and networking
iroh = "0.12"
quiche = "0.20"


# IPFS related
cid = "0.10"
multihash = "0.18"
multibase = "0.9"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Video processing
ffmpeg-next = "6.1"

# Authentication
jsonwebtoken = "9.2"

# Logging and metrics
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
prometheus = "0.13"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Testing
tokio-test = "0.4"
