[package]
name = "hybrid-streaming-streaming"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
hybrid-streaming-common = { path = "../common" }
hybrid-streaming-storage = { path = "../storage" }

# Networking and protocols
quiche.workspace = true
tokio.workspace = true
hyper = { version = "1.1", features = ["full"] }
bytes = "1.5"
futures = "0.3"

# HLS specific
m3u8-rs = "5.0"
rust-crypto = "0.2"

# Metrics and monitoring
metrics = "0.21"
metrics-exporter-prometheus = "0.12"

# Error handling and logging
thiserror.workspace = true
tracing.workspace = true
anyhow.workspace = true

[dev-dependencies]
tokio-test.workspace = true
wiremock = "0.5"
