package horizon:extension;

interface logger {
    log: func(msg: string);
}

interface network {
    record access {
        read: string,
        write: string,
        document-id: string
    }
    record doc {
        document-id: string
    }
    resource document {
        constructor();
        create: func() -> result<access>;
        load: func(ticket: string) -> result<doc>;
        read-key: func (document-id: string, key: string) -> list<u8>;
        add-key-value: func (document-id: string, key: string, value: list<u8>);
    }
}
interface blob {
    read-collections: func() -> list<u8>;
}
world extension {
	export handle: func(event: string) -> string;
	import logger;
	import network;
}
