package horizon:extension;

interface logger {
    log: func(msg: string);
}
interface network {
    resource document {
        constructor();
        read-key: func (key: string) -> list<u8>;
        add-key-value: func (key: string, value: list<u8>);
    }
}
interface blob {
    read-collections: func() -> list<u8>;
}
world extension {
	export handle: func(event: string) -> string;
	import logger;
	import network;
}
